# Generated by Django 5.2.10 on 2026-01-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_make_custom_field_label_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='private_testmode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(
                default=True,
                help_text='Inactive questions are not shown to customers during checkout or check-in. Unlike hidden questions (which are system-level), active controls visibility and can be toggled by event organizers.',
                verbose_name='Active'
            ),
        ),
        migrations.AlterField(
            model_name='talkquestion',
            name='contains_personal_data',
            field=models.BooleanField(default=False, help_text='If a user deletes their account, responses containing personal data will be removed, too.', verbose_name='Responses contain personal data'),
        ),
        migrations.AlterField(
            model_name='talkquestion',
            name='variant',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'Text (one-line)'), ('text', 'Multi-line text'), ('url', 'URL'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'Confirmation'), ('file', 'File upload'), ('choices', 'Radio button (Choose one option)'), ('multiple_choice', 'Checkbox (Choose one or several options)')], default='string', max_length=15),
        ),
    ]
